name: Node basic build
'on': push
jobs:
  build-node:
    name: Build Node
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - run: node --version
        name: Check Node Version
      - run: npm --version
        name: Check NPM Version
      - uses: actions/checkout@v2
        name: Checkout code
      - run: npm install
        name: Install NPM packages
      - run: export NODE_OPTIONS=--max_old_space_size=16384
        name: Max Memory
      - run: npm run-script build
        name: Run application
